<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DataController extends Controller
{
   public function index() {

       $products = [
           [
               "name" => "Logitech G502 Lightspeed",
               "price" => 2089999,
               "image" => "img/barang/image 13.png"
           ],
           [
               "name" => "Razer DeathAdder V3 Hyperspeed",
               "price" => 1399099,
               "image" => "img/barang/image 14.png"
           ],
           [
               "name" => "ONIKUMA K9 RGB Cat Ears",
               "price" => 298000,
               "image" => "img/barang/image 12.png"
           ],
           [
               "name" => "ASUS TUF Gaming A15 FA506",
               "price" => 13024999,
               "image" => "img/barang/image 15.png"
           ],
           [
               "name" => "PS5 Slim Console Disc",
               "price" => 9679998,
               "image" => "img/barang/image 16.png"
           ],
           [
               "name" => "Logitech G715 TKL",
               "price" => 2699998,
               "image" => "img/barang/image 17.png"
           ],
       ];
       return view('web', compact('products'));
   }

    public function produk()
    {

        $produk = [
            'nama' => 'Laptop ASUS TUF GAMING F15',
            'harga' => 12999000,
            'harga_diskon' => 15999000,
            'rating' => 4.8,
            'ulasan' => 1236,
            'deskripsi' => 'Nikmati performa gaming maksimal dengan prosesor Intel, layar 144Hz, kartu grafis RTX, dan desain tahan banting khas TUF.',
            'gambar' => [
                'img/oang-2.jpg',
                'img/orang-1.jpg',
                'img/orang-3.jpg',
                'img/orang-4.jpg',
            ]
        ];

        return view('detail', compact('produk'));
    }

    private
        $products = [

        [
            "id" => 1,
            "name" => "ASUS ROG Zephyrus G14",
            "desc" => "Ryzen 9 8945HS, RTX 4060, layar 14 inci QHD 120Hz, RAM 16GB DDR5, SSD 1TB",
            "price" => 24999000,
            "old_price" => 27999000,
            "discount" => "10%",
            "location" => "Jakarta",
            "rating" => "⭐⭐⭐⭐⭐",
            "image" => "img/barang/ASUS ROG Zephyrus G14.jpeg",
            "category" => "laptop",
        ],
        [
            "id" => 2,
            "name" => "Acer Predator Helios 300",
            "desc" => "Intel Core i7-10750H, RTX 3060, layar 15.6 inci FHD 144Hz, RAM 16GB, SSD 512GB",
            "price" => 19999000,
            "old_price" => 22999000,
            "discount" => "13%",
            "location" => "Bandung",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/Acer Predator Helios 300.webp",
            "category" => "laptop",
        ],
        [
            "id" => 3,
            "name" => "Lenovo Legion 5 Pro",
            "desc" => "Ryzen 7 5800H, RTX 3070, layar 16 inci WQXGA 165Hz, RAM 16GB, SSD 1TB",
            "price" => 23999000,
            "old_price" => null,
            "discount" => null,
            "location" => "Surabaya",
            "rating" => "⭐⭐⭐⭐⭐",
            "image" => "img/barang/Lenovo Legion 5 Pro.jpg",
            "category" => "laptop",
        ],
        [
            "id" => 4,
            "name" => "MSI Katana GF66",
            "desc" => "Intel Core i5-11400H, RTX 3050Ti, layar 15.6 inci FHD 144Hz, RAM 8GB, SSD 512GB",
            "price" => 15999000,
            "old_price" => 17999000,
            "discount" => "11%",
            "location" => "Medan",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/MSI Katana GF66.png",
            "category" => "laptop",
        ],
        [
            "id" => 5,
            "name" => "HP Omen 16",
            "desc" => "Intel Core i7-12700H, RTX 3060, layar 16.1 inci FHD 165Hz, RAM 16GB, SSD 512GB",
            "price" => 21999000,
            "old_price" => null,
            "discount" => null,
            "location" => "Yogyakarta",
            "rating" => "⭐⭐⭐⭐⭐",
            "image" => "img/barang/HP Omen 16.jpg",
            "category" => "laptop",
        ],


        [
            "id" => 6,
            "name" => "iPhone 14 Pro Max",
            "desc" => "Apple A16 Bionic, layar 6.7 inci Super Retina XDR OLED, 512GB storage, kamera 48MP",
            "price" => 20999000,
            "old_price" => 22999000,
            "discount" => "9%",
            "location" => "Jakarta",
            "rating" => "⭐⭐⭐⭐⭐",
            "image" => "img/barang/iPhone 14 Pro Max.jpg",
            "category" => "handphone",
        ],
        [
            "id" => 7,
            "name" => "Samsung Galaxy S23 Ultra",
            "desc" => "Snapdragon 8 Gen 2, layar 6.8 inci QHD+ AMOLED 120Hz, RAM 12GB, storage 512GB, kamera 200MP",
            "price" => 19999000,
            "old_price" => null,
            "discount" => null,
            "location" => "Bandung",
            "rating" => "⭐⭐⭐⭐⭐",
            "image" => "img/barang/Samsung Galaxy S23 Ultra.jpg",
            "category" => "handphone",
        ],
        [
            "id" => 8,
            "name" => "Xiaomi 13 Pro",
            "desc" => "Snapdragon 8 Gen 2, layar 6.73 inci AMOLED 120Hz, RAM 12GB, storage 256GB, kamera Leica 50MP",
            "price" => 13999000,
            "old_price" => 15999000,
            "discount" => "12%",
            "location" => "Surabaya",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/Xiaomi 13 Pro.jpg",
            "category" => "handphone",
        ],
        [
            "id" => 9,
            "name" => "iPad Pro 12.9 (M2)",
            "desc" => "Apple M2 chip, layar 12.9 inci Liquid Retina XDR, storage 256GB, Wi-Fi + Cellular, Apple Pencil support",
            "price" => 18999000,
            "old_price" => 19999000,
            "discount" => "5%",
            "location" => "Medan",
            "rating" => "⭐⭐⭐⭐⭐",
            "image" => "img/barang/iPad Pro 12.9 (M2).png",
            "category" => "handphone",
        ],
        [
            "id" => 10,
            "name" => "Realme GT Neo 5",
            "desc" => "Snapdragon 8+ Gen 1, layar 6.74 inci AMOLED 144Hz, RAM 16GB, storage 1TB, fast charging 240W",
            "price" => 8999000,
            "old_price" => 9999000,
            "discount" => "10%",
            "location" => "Semarang",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/Realme GT Neo 5.jpg",
            "category" => "handphone",
        ],


        [
            "id" => 11,
            "name" => "iMac 24 inci M1",
            "desc" => "Apple M1, layar 24 inci 4.5K Retina, GPU 8-core, RAM 8GB, SSD 256GB",
            "price" => 19999000,
            "old_price" => 21999000,
            "discount" => "9%",
            "location" => "Jakarta",
            "rating" => "⭐⭐⭐⭐⭐",
            "image" => "img/barang/iMac 24 inci M1.jpg",
            "category" => "pc",
        ],
        [
            "id" => 12,
            "name" => "HP All-in-One 27",
            "desc" => "Intel Core i5-12400, layar 27 inci FHD, RAM 16GB, SSD 512GB",
            "price" => 11999000,
            "old_price" => null,
            "discount" => null,
            "location" => "Bandung",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/HP All-in-One 27.avif",
            "category" => "pc",
        ],
        [
            "id" => 13,
            "name" => "ASUS ExpertCenter D7",
            "desc" => "Intel Core i7-11700, GPU GTX 1660 Super, RAM 16GB, SSD 512GB",
            "price" => 13999000,
            "old_price" => 14999000,
            "discount" => "7%",
            "location" => "Surabaya",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/ASUS ExpertCenter D7.jpg",
            "category" => "pc",
        ],
        [
            "id" => 14,
            "name" => "Lenovo IdeaCentre 3",
            "desc" => "AMD Ryzen 5 4600G, Vega integrated graphics, RAM 8GB, SSD 512GB",
            "price" => 9999000,
            "old_price" => 10999000,
            "discount" => "9%",
            "location" => "Medan",
            "rating" => "⭐⭐⭐",
            "image" => "img/barang/Lenovo IdeaCentre 3.jpeg",
            "category" => "pc",
        ],
        [
            "id" => 15,
            "name" => "MSI Pro DP21",
            "desc" => "Mini desktop, Intel Core i3-12100, RAM 8GB, SSD 256GB, compact design",
            "price" => 6499000,
            "old_price" => 6999000,
            "discount" => "7%",
            "location" => "Semarang",
            "rating" => "⭐⭐⭐",
            "image" => "img/barang/MSI Pro DP21.png",
            "category" => "pc",
        ],


        [
            "id" => 16,
            "name" => "Intel NUC 12",
            "desc" => "Mini PC, Intel Core i7-1260P, RAM 16GB, SSD 512GB, Wi-Fi 6",
            "price" => 10999000,
            "old_price" => null,
            "discount" => null,
            "location" => "Jakarta",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/Intel NUC 12.jpeg",
            "category" => "mini-pc",
        ],
        [
            "id" => 17,
            "name" => "ASUS PN50",
            "desc" => "Mini PC, AMD Ryzen 5 4500U, Vega 8 graphics, RAM 8GB, SSD 256GB",
            "price" => 7499000,
            "old_price" => 7999000,
            "discount" => "6%",
            "location" => "Bandung",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/ASUS PN50.jpeg",
            "category" => "mini-pc",
        ],
        [
            "id" => 18,
            "name" => "Beelink SER5",
            "desc" => "Mini PC, AMD Ryzen 7 5800H, RAM 16GB, SSD 512GB, Wi-Fi 6",
            "price" => 6999000,
            "old_price" => 7499000,
            "discount" => "7%",
            "location" => "Surabaya",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/Beelink SER5.jpeg",
            "category" => "mini-pc",
        ],
        [
            "id" => 18,
            "name" => "Mac Mini M2",
            "desc" => "Apple M2 chip, RAM 8GB, SSD 256GB, macOS Ventura",
            "price" => 8999000,
            "old_price" => null,
            "discount" => null,
            "location" => "Medan",
            "rating" => "⭐⭐⭐⭐⭐",
            "image" => "img/barang/Mac Mini M2.jpeg",
            "category" => "mini-pc",
        ],
        [
            "id" => 19,
            "name" => "MINISFORUM UM700",
            "desc" => "Mini PC, AMD Ryzen 7 3750H, Vega 10 graphics, RAM 16GB, SSD 512GB",
            "price" => 5999000,
            "old_price" => 6499000,
            "discount" => "8%",
            "location" => "Semarang",
            "rating" => "⭐⭐⭐",
            "image" => "img/barang/MINISFORUM UM700.jpg",
            "category" => "mini-pc",
        ],


        [
            "id" => 20,
            "name" => "LG Ultragear 27GL850",
            "desc" => "27 inci QHD, Nano IPS, refresh rate 144Hz, 1ms response, G-Sync compatible",
            "price" => 7499000,
            "old_price" => 7999000,
            "discount" => "6%",
            "location" => "Jakarta",
            "rating" => "⭐⭐⭐⭐⭐",
            "image" => "img/barang/LG Ultragear 27GL850.jpeg",
            "category" => "monitor",
        ],
        [
            "id" => 21,
            "name" => "Samsung Odyssey G7",
            "desc" => "32 inci QHD curved, VA panel, refresh rate 240Hz, HDR600, G-Sync/FreeSync",
            "price" => 8999000,
            "old_price" => null,
            "discount" => null,
            "location" => "Bandung",
            "rating" => "⭐⭐⭐⭐⭐",
            "image" => "img/barang/Samsung Odyssey G7.jpg",
            "category" => "monitor",
        ],
        [
            "id" => 22,
            "name" => "Acer Nitro VG271",
            "desc" => "27 inci FHD IPS, refresh rate 144Hz, 1ms VRB, FreeSync",
            "price" => 3499000,
            "old_price" => 3999000,
            "discount" => "12%",
            "location" => "Surabaya",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/Acer Nitro VG271.jpg",
            "category" => "monitor",
        ],
        [
            "id" => 23,
            "name" => "ASUS TUF VG249Q",
            "desc" => "24 inci IPS FHD, refresh rate 144Hz, FreeSync/Adaptive-Sync, 1ms MPRT",
            "price" => 2999000,
            "old_price" => 3299000,
            "discount" => "9%",
            "location" => "Medan",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/ASUS TUF VG249Q.jpg",
            "category" => "monitor",
        ],
        [
            "id" => 24,
            "name" => "Xiaomi Curved Gaming Monitor",
            "desc" => "34 inci WQHD curved, VA panel, refresh rate 144Hz, ultra-wide 21:9",
            "price" => 4999000,
            "old_price" => null,
            "discount" => null,
            "location" => "Semarang",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/Xiaomi Curved Gaming Monitor.jpeg",
            "category" => "monitor",
        ],


        [
            "id" => 25,
            "name" => "TP-Link Archer AX73",
            "desc" => "WiFi 6 Router AX5400, dual-band, 6 antena, kecepatan hingga 5400Mbps",
            "price" => 1899000,
            "old_price" => 2099000,
            "discount" => "10%",
            "location" => "Jakarta",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/TP-Link Archer AX73.jpeg",
            "category" => "networking",
        ],
        [
            "id" => 26,
            "name" => "ASUS RT-AX88U",
            "desc" => "Gaming Router WiFi 6 AX6000, 8 port LAN Gigabit, AiMesh support",
            "price" => 3999000,
            "old_price" => null,
            "discount" => null,
            "location" => "Bandung",
            "rating" => "⭐⭐⭐⭐⭐",
            "image" => "img/barang/ASUS RT-AX88U.jpeg",
            "category" => "networking",
        ],
        [
            "id" => 27,
            "name" => "MikroTik hAP ac2",
            "desc" => "Dual-band Router, 5 port Gigabit LAN, WiFi 5, CPU quad-core 716MHz",
            "price" => 1299000,
            "old_price" => 1499000,
            "discount" => "13%",
            "location" => "Surabaya",
            "rating" => "⭐⭐⭐",
            "image" => "img/barang/MikroTik hAP ac2.jpeg",
            "category" => "networking",
        ],
        [
            "id" => 28,
            "name" => "Ubiquiti UniFi 6 Lite",
            "desc" => "Access Point WiFi 6 dual-band, kecepatan hingga 1.5Gbps, desain compact",
            "price" => 2199000,
            "old_price" => 2399000,
            "discount" => "8%",
            "location" => "Medan",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/Ubiquiti UniFi 6 Lite.jpeg",
            "category" => "networking",
        ],
        [
            "id" => 29,
            "name" => "D-Link DIR-X5460",
            "desc" => "Router WiFi 6 AX5400, 6 antena, MU-MIMO, OFDMA",
            "price" => 1699000,
            "old_price" => null,
            "discount" => null,
            "location" => "Semarang",
            "rating" => "⭐⭐⭐",
            "image" => "img/barang/D-Link DIR-X5460.jpg",
            "category" => "networking",
        ],


        [
            "id" => 30,
            "name" => "Apple Watch Series 8",
            "desc" => "41mm, GPS + Cellular, layar Retina Always-On, sensor kesehatan lengkap, tahan air 50m",
            "price" => 7999000,
            "old_price" => 8499000,
            "discount" => "6%",
            "location" => "Jakarta",
            "rating" => "⭐⭐⭐⭐⭐",
            "image" => "img/barang/Apple Watch Series 8.jpeg",
            "category" => "smartwatch",
        ],
        [
            "id" => 31,
            "name" => "Samsung Galaxy Watch 5 Pro",
            "desc" => "46mm, layar Super AMOLED, case Titanium, GPS, baterai tahan lama, fitur kesehatan",
            "price" => 6499000,
            "old_price" => null,
            "discount" => null,
            "location" => "Bandung",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/Samsung Galaxy Watch 5 Pro.jpeg",
            "category" => "smartwatch",
        ],
        [
            "id" => 32,
            "name" => "Garmin Fenix 7",
            "desc" => "Multisport GPS Watch, layar transflektif 1.3 inci, navigasi lengkap, baterai hingga 18 hari",
            "price" => 9999000,
            "old_price" => 10999000,
            "discount" => "9%",
            "location" => "Surabaya",
            "rating" => "⭐⭐⭐⭐⭐",
            "image" => "img/barang/Garmin Fenix 7.jpg",
            "category" => "smartwatch",
        ],
        [
            "id" => 33,
            "name" => "Amazfit GTR 4",
            "desc" => "Layar AMOLED 1,43 inci (466×466, Always-on Display), Bodi aluminium + bezel stainless steel ",
            "price" => 1299000,
            "old_price" => 1499000,
            "discount" => "13%",
            "location" => "Medan",
            "rating" => "⭐⭐⭐",
            "image" => "img/barang/Amazfit GTR 4.jpg",
            "category" => "smartwatch",
        ],
        [
            "id" => 34,
            "name" => "Huawei Watch GT 3",
            "desc" => "46mm, layar AMOLED, GPS, sensor SpO2, baterai hingga 2 minggu",
            "price" => 3299000,
            "old_price" => null,
            "discount" => null,
            "location" => "Semarang",
            "rating" => "⭐⭐⭐⭐",
            "image" => "img/barang/Huawei Watch GT 3 Pro.jpg",
            "category" => "smartwatch",
        ],
    ];

    public function shop() {

        $products = [

            [
                "id" => 1,
                "name" => "ASUS ROG Zephyrus G14",
                "desc" => "Ryzen 9 8945HS, RTX 4060, layar 14 inci QHD 120Hz, RAM 16GB DDR5, SSD 1TB",
                "price" => 24999000,
                "old_price" => 27999000,
                "discount" => "10%",
                "location" => "Jakarta",
                "rating" => "⭐⭐⭐⭐⭐",
                "image" => "img/barang/ASUS ROG Zephyrus G14.jpeg",
                "category" => "laptop",
            ],
            [
                "id" => 2,
                "name" => "Acer Predator Helios 300",
                "desc" => "Intel Core i7-10750H, RTX 3060, layar 15.6 inci FHD 144Hz, RAM 16GB, SSD 512GB",
                "price" => 19999000,
                "old_price" => 22999000,
                "discount" => "13%",
                "location" => "Bandung",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/Acer Predator Helios 300.webp",
                "category" => "laptop",
            ],
            [
                "id" => 3,
                "name" => "Lenovo Legion 5 Pro",
                "desc" => "Ryzen 7 5800H, RTX 3070, layar 16 inci WQXGA 165Hz, RAM 16GB, SSD 1TB",
                "price" => 23999000,
                "old_price" => null,
                "discount" => null,
                "location" => "Surabaya",
                "rating" => "⭐⭐⭐⭐⭐",
                "image" => "img/barang/Lenovo Legion 5 Pro.jpg",
                "category" => "laptop",
            ],
            [
                "id" => 4,
                "name" => "MSI Katana GF66",
                "desc" => "Intel Core i5-11400H, RTX 3050Ti, layar 15.6 inci FHD 144Hz, RAM 8GB, SSD 512GB",
                "price" => 15999000,
                "old_price" => 17999000,
                "discount" => "11%",
                "location" => "Medan",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/MSI Katana GF66.png",
                "category" => "laptop",
            ],
            [
                "id" => 5,
                "name" => "HP Omen 16",
                "desc" => "Intel Core i7-12700H, RTX 3060, layar 16.1 inci FHD 165Hz, RAM 16GB, SSD 512GB",
                "price" => 21999000,
                "old_price" => null,
                "discount" => null,
                "location" => "Yogyakarta",
                "rating" => "⭐⭐⭐⭐⭐",
                "image" => "img/barang/HP Omen 16.jpg",
                "category" => "laptop",
            ],


            [
                "id" => 6,
                "name" => "iPhone 14 Pro Max",
                "desc" => "Apple A16 Bionic, layar 6.7 inci Super Retina XDR OLED, 512GB storage, kamera 48MP",
                "price" => 20999000,
                "old_price" => 22999000,
                "discount" => "9%",
                "location" => "Jakarta",
                "rating" => "⭐⭐⭐⭐⭐",
                "image" => "img/barang/iPhone 14 Pro Max.jpg",
                "category" => "handphone",
            ],
            [
                "id" => 7,
                "name" => "Samsung Galaxy S23 Ultra",
                "desc" => "Snapdragon 8 Gen 2, layar 6.8 inci QHD+ AMOLED 120Hz, RAM 12GB, storage 512GB, kamera 200MP",
                "price" => 19999000,
                "old_price" => null,
                "discount" => null,
                "location" => "Bandung",
                "rating" => "⭐⭐⭐⭐⭐",
                "image" => "img/barang/Samsung Galaxy S23 Ultra.jpg",
                "category" => "handphone",
            ],
            [
                "id" => 8,
                "name" => "Xiaomi 13 Pro",
                "desc" => "Snapdragon 8 Gen 2, layar 6.73 inci AMOLED 120Hz, RAM 12GB, storage 256GB, kamera Leica 50MP",
                "price" => 13999000,
                "old_price" => 15999000,
                "discount" => "12%",
                "location" => "Surabaya",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/Xiaomi 13 Pro.jpg",
                "category" => "handphone",
            ],
            [
                "id" => 9,
                "name" => "iPad Pro 12.9 (M2)",
                "desc" => "Apple M2 chip, layar 12.9 inci Liquid Retina XDR, storage 256GB, Wi-Fi + Cellular, Apple Pencil support",
                "price" => 18999000,
                "old_price" => 19999000,
                "discount" => "5%",
                "location" => "Medan",
                "rating" => "⭐⭐⭐⭐⭐",
                "image" => "img/barang/iPad Pro 12.9 (M2).png",
                "category" => "handphone",
            ],
            [
                "id" => 10,
                "name" => "Realme GT Neo 5",
                "desc" => "Snapdragon 8+ Gen 1, layar 6.74 inci AMOLED 144Hz, RAM 16GB, storage 1TB, fast charging 240W",
                "price" => 8999000,
                "old_price" => 9999000,
                "discount" => "10%",
                "location" => "Semarang",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/Realme GT Neo 5.jpg",
                "category" => "handphone",
            ],

            [
                "id" => 11,
                "name" => "iMac 24 inci M1",
                "desc" => "Apple M1, layar 24 inci 4.5K Retina, GPU 8-core, RAM 8GB, SSD 256GB",
                "price" => 19999000,
                "old_price" => 21999000,
                "discount" => "9%",
                "location" => "Jakarta",
                "rating" => "⭐⭐⭐⭐⭐",
                "image" => "img/barang/iMac 24 inci M1.jpg",
                "category" => "pc",
            ],
            [
                "id" => 12,
                "name" => "HP All-in-One 27",
                "desc" => "Intel Core i5-12400, layar 27 inci FHD, RAM 16GB, SSD 512GB",
                "price" => 11999000,
                "old_price" => null,
                "discount" => null,
                "location" => "Bandung",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/HP All-in-One 27.avif",
                "category" => "pc",
            ],
            [
                "id" => 13,
                "name" => "ASUS ExpertCenter D7",
                "desc" => "Intel Core i7-11700, GPU GTX 1660 Super, RAM 16GB, SSD 512GB",
                "price" => 13999000,
                "old_price" => 14999000,
                "discount" => "7%",
                "location" => "Surabaya",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/ASUS ExpertCenter D7.jpg",
                "category" => "pc",
            ],
            [
                "id" => 14,
                "name" => "Lenovo IdeaCentre 3",
                "desc" => "AMD Ryzen 5 4600G, Vega integrated graphics, RAM 8GB, SSD 512GB",
                "price" => 9999000,
                "old_price" => 10999000,
                "discount" => "9%",
                "location" => "Medan",
                "rating" => "⭐⭐⭐",
                "image" => "img/barang/Lenovo IdeaCentre 3.jpeg",
                "category" => "pc",
            ],
            [
                "id" => 15,
                "name" => "MSI Pro DP21",
                "desc" => "Mini desktop, Intel Core i3-12100, RAM 8GB, SSD 256GB, compact design",
                "price" => 6499000,
                "old_price" => 6999000,
                "discount" => "7%",
                "location" => "Semarang",
                "rating" => "⭐⭐⭐",
                "image" => "img/barang/MSI Pro DP21.png",
                "category" => "pc",
            ],

            [
                "id" => 16,
                "name" => "Intel NUC 12",
                "desc" => "Mini PC, Intel Core i7-1260P, RAM 16GB, SSD 512GB, Wi-Fi 6",
                "price" => 10999000,
                "old_price" => null,
                "discount" => null,
                "location" => "Jakarta",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/Intel NUC 12.jpeg",
                "category" => "mini-pc",
            ],
            [
                "id" => 17,
                "name" => "ASUS PN50",
                "desc" => "Mini PC, AMD Ryzen 5 4500U, Vega 8 graphics, RAM 8GB, SSD 256GB",
                "price" => 7499000,
                "old_price" => 7999000,
                "discount" => "6%",
                "location" => "Bandung",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/ASUS PN50.jpeg",
                "category" => "mini-pc",
            ],
            [
                "id" => 18,
                "name" => "Beelink SER5",
                "desc" => "Mini PC, AMD Ryzen 7 5800H, RAM 16GB, SSD 512GB, Wi-Fi 6",
                "price" => 6999000,
                "old_price" => 7499000,
                "discount" => "7%",
                "location" => "Surabaya",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/Beelink SER5.jpeg",
                "category" => "mini-pc",
            ],
            [
                "id" => 18,
                "name" => "Mac Mini M2",
                "desc" => "Apple M2 chip, RAM 8GB, SSD 256GB, macOS Ventura",
                "price" => 8999000,
                "old_price" => null,
                "discount" => null,
                "location" => "Medan",
                "rating" => "⭐⭐⭐⭐⭐",
                "image" => "img/barang/Mac Mini M2.jpeg",
                "category" => "mini-pc",
            ],
            [
                "id" => 19,
                "name" => "MINISFORUM UM700",
                "desc" => "Mini PC, AMD Ryzen 7 3750H, Vega 10 graphics, RAM 16GB, SSD 512GB",
                "price" => 5999000,
                "old_price" => 6499000,
                "discount" => "8%",
                "location" => "Semarang",
                "rating" => "⭐⭐⭐",
                "image" => "img/barang/MINISFORUM UM700.jpg",
                "category" => "mini-pc",
            ],

            [
                "id" => 20,
                "name" => "LG Ultragear 27GL850",
                "desc" => "27 inci QHD, Nano IPS, refresh rate 144Hz, 1ms response, G-Sync compatible",
                "price" => 7499000,
                "old_price" => 7999000,
                "discount" => "6%",
                "location" => "Jakarta",
                "rating" => "⭐⭐⭐⭐⭐",
                "image" => "img/barang/LG Ultragear 27GL850.jpeg",
                "category" => "monitor",
            ],
            [
                "id" => 21,
                "name" => "Samsung Odyssey G7",
                "desc" => "32 inci QHD curved, VA panel, refresh rate 240Hz, HDR600, G-Sync/FreeSync",
                "price" => 8999000,
                "old_price" => null,
                "discount" => null,
                "location" => "Bandung",
                "rating" => "⭐⭐⭐⭐⭐",
                "image" => "img/barang/Samsung Odyssey G7.jpg",
                "category" => "monitor",
            ],
            [
                "id" => 22,
                "name" => "Acer Nitro VG271",
                "desc" => "27 inci FHD IPS, refresh rate 144Hz, 1ms VRB, FreeSync",
                "price" => 3499000,
                "old_price" => 3999000,
                "discount" => "12%",
                "location" => "Surabaya",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/Acer Nitro VG271.jpg",
                "category" => "monitor",
            ],
            [
                "id" => 23,
                "name" => "ASUS TUF VG249Q",
                "desc" => "24 inci IPS FHD, refresh rate 144Hz, FreeSync/Adaptive-Sync, 1ms MPRT",
                "price" => 2999000,
                "old_price" => 3299000,
                "discount" => "9%",
                "location" => "Medan",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/ASUS TUF VG249Q.jpg",
                "category" => "monitor",
            ],
            [
                "id" => 24,
                "name" => "Xiaomi Curved Gaming Monitor",
                "desc" => "34 inci WQHD curved, VA panel, refresh rate 144Hz, ultra-wide 21:9",
                "price" => 4999000,
                "old_price" => null,
                "discount" => null,
                "location" => "Semarang",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/Xiaomi Curved Gaming Monitor.jpeg",
                "category" => "monitor",
            ],

            [
                "id" => 25,
                "name" => "TP-Link Archer AX73",
                "desc" => "WiFi 6 Router AX5400, dual-band, 6 antena, kecepatan hingga 5400Mbps",
                "price" => 1899000,
                "old_price" => 2099000,
                "discount" => "10%",
                "location" => "Jakarta",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/TP-Link Archer AX73.jpeg",
                "category" => "networking",
            ],
            [
                "id" => 26,
                "name" => "ASUS RT-AX88U",
                "desc" => "Gaming Router WiFi 6 AX6000, 8 port LAN Gigabit, AiMesh support",
                "price" => 3999000,
                "old_price" => null,
                "discount" => null,
                "location" => "Bandung",
                "rating" => "⭐⭐⭐⭐⭐",
                "image" => "img/barang/ASUS RT-AX88U.jpeg",
                "category" => "networking",
            ],
            [
                "id" => 27,
                "name" => "MikroTik hAP ac2",
                "desc" => "Dual-band Router, 5 port Gigabit LAN, WiFi 5, CPU quad-core 716MHz",
                "price" => 1299000,
                "old_price" => 1499000,
                "discount" => "13%",
                "location" => "Surabaya",
                "rating" => "⭐⭐⭐",
                "image" => "img/barang/MikroTik hAP ac2.jpeg",
                "category" => "networking",
            ],
            [
                "id" => 28,
                "name" => "Ubiquiti UniFi 6 Lite",
                "desc" => "Access Point WiFi 6 dual-band, kecepatan hingga 1.5Gbps, desain compact",
                "price" => 2199000,
                "old_price" => 2399000,
                "discount" => "8%",
                "location" => "Medan",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/Ubiquiti UniFi 6 Lite.jpeg",
                "category" => "networking",
            ],
            [
                "id" => 29,
                "name" => "D-Link DIR-X5460",
                "desc" => "Router WiFi 6 AX5400, 6 antena, MU-MIMO, OFDMA",
                "price" => 1699000,
                "old_price" => null,
                "discount" => null,
                "location" => "Semarang",
                "rating" => "⭐⭐⭐",
                "image" => "img/barang/D-Link DIR-X5460.jpg",
                "category" => "networking",
            ],

            [
                "id" => 30,
                "name" => "Apple Watch Series 8",
                "desc" => "41mm, GPS + Cellular, layar Retina Always-On, sensor kesehatan lengkap, tahan air 50m",
                "price" => 7999000,
                "old_price" => 8499000,
                "discount" => "6%",
                "location" => "Jakarta",
                "rating" => "⭐⭐⭐⭐⭐",
                "image" => "img/barang/Apple Watch Series 8.jpeg",
                "category" => "smartwatch",
            ],
            [
                "id" => 31,
                "name" => "Samsung Galaxy Watch 5 Pro",
                "desc" => "46mm, layar Super AMOLED, case Titanium, GPS, baterai tahan lama, fitur kesehatan",
                "price" => 6499000,
                "old_price" => null,
                "discount" => null,
                "location" => "Bandung",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/Samsung Galaxy Watch 5 Pro.jpeg",
                "category" => "smartwatch",
            ],
            [
                "id" => 32,
                "name" => "Garmin Fenix 7",
                "desc" => "Multisport GPS Watch, layar transflektif 1.3 inci, navigasi lengkap, baterai hingga 18 hari",
                "price" => 9999000,
                "old_price" => 10999000,
                "discount" => "9%",
                "location" => "Surabaya",
                "rating" => "⭐⭐⭐⭐⭐",
                "image" => "img/barang/Garmin Fenix 7.jpg",
                "category" => "smartwatch",
            ],
            [
                "id" => 33,
                "name" => "Amazfit GTR 4",
                "desc" => "Layar AMOLED 1,43 inci (466×466, Always-on Display), Bodi aluminium + bezel stainless steel ",
                "price" => 1299000,
                "old_price" => 1499000,
                "discount" => "13%",
                "location" => "Medan",
                "rating" => "⭐⭐⭐",
                "image" => "img/barang/Amazfit GTR 4.jpg",
                "category" => "smartwatch",
            ],
            [
                "id" => 34,
                "name" => "Huawei Watch GT 3",
                "desc" => "46mm, layar AMOLED, GPS, sensor SpO2, baterai hingga 2 minggu",
                "price" => 3299000,
                "old_price" => null,
                "discount" => null,
                "location" => "Semarang",
                "rating" => "⭐⭐⭐⭐",
                "image" => "img/barang/Huawei Watch GT 3 Pro.jpg",
                "category" => "smartwatch",
            ],
        ];

        return view('shop', compact('products'));

        $products = $this->products;
        return view('shop', compact('products'));

        }


    public function detail($id) {
        $product = collect($this->products)->firstWhere('id', $id);

        if (!$product) {
            abort(404);
        }

        return view('product-detail', compact('product'));
    }



}
